### ISSUE TITLE
Remove upload_subfolder() in favor of using upload_to() that accepts path or callable like FileField

### ISSUE THREAD

**Issue by thecardcheat** [edoburu/django-private-storage#13] opened 2017-11-01 04:08 UTC
I can't think of a reason not to keep `upload_to` like it is in `FileField`, so if there is one, please clarify. I think it will continue to be a source of confusion like #3 and potential bugs like #11 and it doesn't add anything as far as I can tell.

**Comment by vdboor** [comment] 2017-11-20 15:41
The problem is that `upload_to` is already somewhat reserved by Django, and using it broke in other places. Maybe this is fixed in modern Django versions, but that's why I've opted to use a different field instead. Perhaps a warning against `upload_to` would also help?

**Comment by vdboor** [comment] 2018-02-06 10:25
Both formats are now supported in master. Could you please test this latest version? (and tell me which Django version you've tested against?)

**Closed by vdboor** 2018-02-06 10:25 UTC
Labels: help wanted

**Comment by vdboor** [comment] 2018-02-06 11:41
Update, after writing unit tests I've released v2.0 :-)
